# Generated by Django 3.0 on 2021-03-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mascota',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
