# Generated by Django 3.0 on 2021-03-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='/static/img/defaultperfil.jpg', upload_to='perfilesmedia'),
        ),
    ]
