# Generated by Django 3.0 on 2021-03-09 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_auto_20210309_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='imagen',
            new_name='imagenu',
        ),
    ]
