# Generated by Django 3.0 on 2021-03-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0006_auto_20210309_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
